### ISSUE TITLE
Executing task on all subscriber

### ISSUE THREAD

**Issue by mandar-bhong** [RichardKnop/machinery#424]
Hi,

How we can execute task on all the registered subscriber and get result.

My scenario is devices is connected with multiple server when user wants to get or notify all connected devices then task need to be executed by all the register server 

Following options can not be opted 
1. Registering every server with new task name and execute task for each server
2. Group task - group task will be executed by only one server among the others

Please suggest how it can be done through machinery library

**Comment by julianwachholz** [comment]
If you use an AMQP broker, you can use a `fanout` exchange type:

In your `config.yml`:
```
amqp:
  binding_key: machinery_task
  exchange: machinery_exchange
  exchange_type: direct
```
