### ISSUE TITLE
Lost periodic task

### ISSUE THREAD

**Issue by agvol** [RichardKnop/machinery#660]
Hi

I have periodic task, but sometime it has been lost. Server use redis.

Task registration. this is one of the attempts:
`err = machineryServer.RegisterPeriodicGroup("*/5 * * * *", "fiveMinutesGroup", 0, fiveMinutesGroup.Tasks...)`

example of data:
![lost](https://user-images.githubusercontent.com/29235185/109868010-34e0ce80-7c78-11eb-8738-b4e2fd688c76.png)

If I change time description to 
`err = machineryServer.RegisterPeriodicGroup("@every 5m", "fiveMinutesGroup", 0, fiveMinutesGroup.Tasks...)`
it working fine, but not precision

how do I figure out what the problem is?
Time on the server synced by chronyd(for testing I try disable chroned, and enable ntpd, but result is some)

Thanks

**Comment by KarlTango** [comment]
Can you provide more information such as your machinery config and excution log?

**Comment by agvol** [comment]
@KarlTango 
sorry, of course:

there is my config
```
---
  broker: redis://localhost:6379
  lock: redis://localhost:6379
  default_queue: machinery_queue
  result_backend: redis://localhost:6379
  results_expire_in: 60
  redis:
      normal_tasks_poll_period: 2000
      delayed_tasks_poll_period: 1000
```

for debug I insert to the fistr line of function debug output
```
func sendSensorsToGraphite() (string, error) {
	Log.Info("Task sendSensorsToGraphite")
```

there is part of output command _journalctl -u machinery | grep "Task sendSensorsToGraphite"_	
```
Mar 04 18:50:00 microserver.home server[29858]: INFO Task sendSensorsToGraphite
Mar 04 18:55:00 microserver.home server[29858]: INFO Task sendSensorsToGraphite
Mar 04 19:00:00 microserver.home server[29858]: INFO Task sendSensorsToGraphite
Mar 04 19:10:00 microserver.home server[29858]: INFO Task sendSensorsToGraphite
Mar 04 19:15:00 microserver.home server[29858]: INFO Task sendSensorsToGraphite
```
as you see, task at Mar 04 19:05:00 is absent

also I already try to set _normal_tasks_poll_period_ and _delayed_tasks_poll_period_ parameters to smallest value, but has no effect, tasks still lost


P.S. I think the problem may be on the side of the external module https://github.com/robfig/cron/
